### PR TITLE
Migrate to new `.csproj` format

### PR DESCRIPTION
**Pull request by YoshiRulz**
edit 2024-04-26:
I recreated my changes on top of the latest commit, taking a slightly different approach. This time I haven't had the chance to test on a Windows machine.
I kept a [backup of the old branch](https://github.com/YoshiRulz/STROOP/tree/new-proj-format-202305).

---

Guess I'm done? Wasn't expecting CI to pass with only a couple of tweaks. Builds and runs on my Win10 machine with VS2022.

Didn't expect it to magically work in Mono, and it doesn't, failing with `Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.` (part of WPF I gather).

see https://github.com/SM64-TAS-ABC/STROOP/issues/72#issuecomment-1180073006

### CODE REVIEW

**Comment by danebou** [comment]
Is the Resource directory copy handled? Before: `<PreBuildEvent>xcopy /E /Y /I "$(ProjectDir)Resources" "$(TargetDir)Resources" /D</PreBuildEvent>`

**Comment by danebou** [comment]
> Is the Resource directory copy handled? Before: `<PreBuildEvent>xcopy /E /Y /I "$(ProjectDir)Resources" "$(TargetDir)Resources" /D</PreBuildEvent>`

Yes it is  		<None Include="Resources\**\*.*" CopyToOutputDirectory="PreserveNewest" />

**Comment by danebou** [comment]
Sorry, forgot about your PR and made some more merge conflicts with recent changes. Can you resolve them? I'll try to keep these files untouched in the meantime.

**Comment by YoshiRulz** [comment]
Please don't make me do that again.

edit: I should add that https://github.com/SM64-TAS-ABC/STROOP/pull/96/commits/440f632c4390e724686a3933ecd07a56385a93ab starts a divide-and-conquer, but I don't actually finish the conquer part in this PR. That's partially because I can't glob if only some files have a property, but also I've been meaning to investigate [a programmatic solution to marking those Designer files](https://gitlab.com/YoshiRulz/yoshis-hawk-thoughts/-/issues/185) but haven't gotten around to it.

**Comment by danebou** [comment]
Thanks. That'd be nice if there was a clean way to handle those.

**Comment by YoshiRulz** [comment]
"Clean" and "the WinForms Designer" are mutually exclusive, I've found.

This was good then? Nothing broke? The next thing I wanted to do was take a look at what tests you have, hopefully get them running without code changes.

**Pull request merged**
