### PR TITLE
Switch to `<EnableDefaultItems>true</EnableDefaultItems>` and re-enable non-string resources on Linux

### PR DESCRIPTION
**Pull request by YoshiRulz**
Following on from https://github.com/SM64-TAS-ABC/STROOP/pull/111#issuecomment-2088817521.

Non-string resources are files embedded in the assembly not with `<EmbeddedResource/>`, but [as an annotated base64 string in a `.resx`](https://github.com/SM64-TAS-ABC/STROOP/blob/3288f690613a99e33e61829306a0a1aea570ae70/STROOP/Map/MapTracker.resx#L121-L140) (these files are ostensibly for i18n, but thanks to the WinForms Designer, I imagine they're more commonly used for icons). I believe this style of embedding is necessary to use images in the Designer, but to be clear, it's *not necessary* if you're willing to ["manually" set `Form.Icon` et al.](https://github.com/TASEmulators/BizHawk/commit/31e621d64e87f9fddf095828ff1fc48797b841ae) with `GetManifestResourceStream`. That's how I initially got BizHawk building on Linux without `System.Resources.Extensions`, and we've kept it since no-one on our team really cares about the Designer, and going back would mean checking in duplicate images to the repo.

### CODE REVIEW

**Comment by danebou** [comment]
Hmm still getting the error `System.IO.FileLoadException: 'Could not load file or assembly 'System.Resources.Extensions, `. But you're proposing removing the icon in InitializeComponent to fix it? Don't see a problem with that. We use the designer still but if it just means the one icon isn't accurate there that's fine.

**Comment by danebou** [comment]
> Hmm still getting the error `System.IO.FileLoadException: 'Could not load file or assembly 'System.Resources.Extensions, `. But you're proposing removing the icon in InitializeComponent to fix it? Don't see a problem with that. We use the designer still but if it just means the one icon isn't accurate there that's fine.

Ah, I see its all images. Linux doesn't work with System.Resources.Extensions? Trying to see if there's any other alternatives

**Comment by danebou** [comment]
Oh it was looking for a version 4 assembly for some reason. Downgrading the system.resources.extensions package to 4.6 solves the problem

**Comment by YoshiRulz** [comment]
~~It doesn't make sense to me why `System.Resources.Extensions` isn't available. The only meaningful difference I can see between STROOP and BizHawk is that we updated to version `7.0.0` at some point, while I played it safe and left it at `6.0.0`:~~
https://github.com/SM64-TAS-ABC/STROOP/blob/3288f690613a99e33e61829306a0a1aea570ae70/STROOP/STROOP.csproj#L98
~~Nevermind, I forgot what `Private` means in MSBuild-speak. I bet if you change it to `<PackageReference Include="System.Resources.Extensions" Version="6.0.0" PrivateAssets="all" />` it will start working.~~ sniped

**Comment by danebou** [comment]
~~Can you throw that change in here, then should be good to go (6 -> 4.6).~~ Nvrmind, I'll commit it

**Comment by YoshiRulz** [comment]
I think `PrivateAssets="all"` would be the better solution anyway if it works.

**Comment by danebou** [comment]
Oh instead of downgrading? Sorry if I merged it too early

**Pull request merged**
